name: 'oss_data_platform'
config-version: 2
version: '1.0.0'

profile: 'datawarehouse'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - target
  - dbt_packages

models:
  oss_data_platform:
    +materialized: table
    datamart:
      +schema: datamart
